<?php
/** @var Attributes $block */

use Magento\Catalog\Block\Product\View\Attributes;

$product = $block->getProduct();
$attribute = $product->getResource()->getAttribute('club_attribute');
$attr_value = $attribute->getFrontend()->getValue($product);
$RegistrationLink = $this->getUrl('shoppingclub/account/create');
$SubscribeLink = $this->getUrl('newsletter/manage');
?>
<div data-bind="scope: 'shoppingclub'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "shoppingclub": {
                    "component": "Rlab_ShoppingClub/js/shoppingclub",
                    "config": {
                        "template": "Rlab_ShoppingClub/shoppingclub",
                        "label": "<?= $attr_value ?>",
                        "RegistrationLink": "<?= $RegistrationLink ?>",
                        "SubscribeLink": "<?= $SubscribeLink ?>"
                   }
                }
            }
        }
    }
}
</script>
